chartmuseum:
  env:
    open:
      DISABLE_API: false
      AUTH_ANONYMOUS_GET: true
    secret:
      BASIC_AUTH_USER: admin # Change me!
      BASIC_AUTH_PASS: admin # Change me!
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 80m
      memory: 64Mi
  persistence:
    enabled: true
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
      ingress.kubernetes.io/ssl-redirect: "false"
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
    hosts:
    - name: cm.192.168.99.101.nip.io # Change me!
      path: /  

jenkins:
  master:
    imageTag: "lts-alpine"
    cpu: "500m"
    memory: "500Mi"
    serviceType: ClusterIP
    serviceAnnotations:
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    GlobalLibraries: true
    installPlugins:
    - durable-task:1.29
    - workflow-durable-task-step:2.28
    - blueocean:1.17.0
    - credentials:2.2.0
    - ec2:1.44.1
    - git:3.10.0
    - git-client:2.8.0
    - github:1.29.4
    - kubernetes:1.16.3
    - pipeline-utility-steps:2.3.0
    - pipeline-model-definition:1.3.9
    - script-security:1.44
    - slack:2.27
    - thinBackup:1.9
    - workflow-aggregator:2.6
    - ssh-slaves:1.29.4
    - ssh-agent:1.17
    - jdk-tool:1.2
    - command-launcher:1.3
    - github-oauth:0.32
    - google-compute-engine:3.3.2
    - pegdown-formatter:1.3
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
        nginx.ingress.kubernetes.io/ssl-redirect: "false"
        nginx.ingress.kubernetes.io/proxy-body-size: 50m
        nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
        ingress.kubernetes.io/ssl-redirect: "false"
        ingress.kubernetes.io/proxy-body-size: 50m
        ingress.kubernetes.io/proxy-request-buffering: "off"
      hostName: jenkins.192.168.99.101.nip.io # Change me!
    CustomConfigMap: true
    CredentialsXmlSecret: jenkins-credentials
    SecretsFilesSecret: jenkins-secrets
    DockerVM: false
  rbac:
    create: true
